application: iosapp-979 
version: 1
runtime: python27
api_version: 1
threadsafe: true

# handlers
handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: my_site.app

# libraries
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

